version: '3.8'

# Train Map Backend - シンプルAPI提供用
services:
  # ====================
  # メインアプリケーション
  # ====================
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: train-map-backend
    ports:
      - "3000:3000"  # アプリケーションポート
    environment:
      # Node.js環境設定
      - NODE_ENV=production
      - PORT=3000
      # タイムゾーン設定
      - TZ=Asia/Tokyo
    volumes:
      # CSVデータを読み取り専用でマウント
      - ./src/data:/app/src/data:ro
    restart: unless-stopped
    # ヘルスチェック設定
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s